# Generated by Django 3.0 on 2021-08-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='documents/')),
                ('label', models.IntegerField(blank=True, null=True, verbose_name='推論結果（ラベル）')),
                ('proba', models.FloatField(default=0.0, verbose_name='信頼度（確率）')),
            ],
        ),
    ]
