# Generated by Django 3.0 on 2021-08-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anataha_dareni_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
