# Generated by Django 3.0 on 2021-08-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anataha_dareni_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='modelfile',
            name='label',
        ),
        migrations.RemoveField(
            model_name='modelfile',
            name='proba',
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
