# Generated by Django 3.0 on 2021-08-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anataha_dareni_app', '0002_modelfile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='label',
            field=models.IntegerField(choices=[(0, '阿部寛'), (1, 'イチロー'), (2, '木村拓哉'), (3, '堺正章'), (4, '田中圭'), (5, '中居正広'), (6, 'ダルビッシュ有'), (7, '福山雅治'), (8, '三浦翔平'), (9, '横浜流星'), (10, '新垣結衣'), (11, '綾瀬はるか'), (12, '有村架純'), (13, '石原さとみ'), (14, '北川景子'), (15, '戸田恵梨香'), (16, '二階堂ふみ'), (17, '橋本環奈'), (18, '浜辺美波'), (19, '広瀬すず'), (20, '該当者なし')], default=20, verbose_name='推論結果（ラベル）'),
        ),
    ]
