# Generated by Django 3.0 on 2021-08-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anataha_dareni_app', '0003_modelfile_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfile',
            name='label',
            field=models.IntegerField(choices=[(0, '阿部寛'), (1, 'イチロー'), (2, '木村拓哉'), (3, '堺正章'), (4, '田中圭'), (5, '中居正広'), (6, 'ダルビッシュ有'), (7, '福山雅治'), (8, '三浦翔平'), (9, '横浜流星'), (10, '該当者なし')], default=10, verbose_name='推論結果（ラベル）'),
        ),
    ]
